version: "2"
linters:
  default: all
  disable:
    - cyclop
    - tagliatelle
    - testpackage
    - exhaustruct
  settings:
    funlen:
      lines: 70
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - github.com/mikolajgasior/octo-linter
            - github.com/mikolajgasior/broccli/v3
            - gopkg.in/yaml.v2
  exclusions:
    generated: disable
    rules:
      - linters:
          - err113
          - exhaustruct
          - funlen
          - varnamelen
          - dupl
        path: _test.go
      - linters:
          - funlen
        path: gen.go
      - linters:
          - dupl
        path: internal/linter/rule/refvars
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines

