---
name: Action with valid name
description: Some description

runs:
  using: "composite"
  steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Calling external action overridden from local source
      uses: mikolajgasior/read-from-local-path@v1
      id: action-1
      #with:
      #  local-src-input-1: "abc123"

    - name: Getting output from previous action
      runs: |
        echo "Below output is not present in action but regular expression matching it is in the config-2 file"
        echo "${{ steps.action-1.outputs.matchme1 }}"

    - name: Call ECR login
      uses: aws-actions/amazon-ecr-login@v2
      id: ecr-login
      with:
        registries: 123456789012345678

    - name: Use output from ECR login
      shell: bash
      run: |
        echo "${{ steps.ecr-login.outputs.docker_username_123456789012345678_dkr_ecr_eu_west_1_amazonaws_com }}"
